In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import spacy
from spacy.tokenizer import Tokenizer

In [48]:
nlp = spacy.load('en_core_web_sm')
tokenizer = Tokenizer(nlp.vocab)

In [49]:
s = "something good\nSomething 2 somethings"
tokens = tokenizer(s)

for token in tokens:
  print(token.lemma_, token.is_stop)

something True
good False

 False
Something True
2 False
somethings False

In [50]:
df = pd.read_csv("dataset.csv")
df.head()

   Unnamed: 0                                         Clickbaits  bait
0           0  Declassified records show American inaction du...     0
1           1  Indian Maoists blamed for the deaths of sixtee...     0
2           2            Yahoo!7 creates joint venture with Xtra     0
3           3     Only Solve This Puzzle If You Love Board Games     1
4           4  Three dead in murder-suicide shooting at South...     0

In [51]:
def calculator(sentence):
    arr = sentence.split(" ")
    totalChar = len(sentence)-(len(arr)-1)
    avgWordLength = totalChar/len(arr)
    
    s = sentence
    tokens = tokenizer(s)
    
    stopWords = 0
    for token in tokens:
        if token.is_stop == True:
            stopWords += 1
    
    stopWordtoContentWord = stopWords/len(arr)
    
    return avgWordLength,stopWordtoContentWord

In [52]:
df["Length"] = np.zeros((len(df["Clickbaits"]),1),dtype=float)
df["AvgWordLength"] = np.zeros((len(df["Clickbaits"]),1),dtype=float)
df["StoptoContent"] = np.zeros((len(df["Clickbaits"]),1),dtype=float)
df["Cardinality"] = np.zeros((len(df["Clickbaits"]),1),dtype=float)

for i in range(len(df["Clickbaits"])):
    df["Length"][i] = len(df["Clickbaits"][i])
    
    avgWordLength,stopWordtoContentWord = calculator(df["Clickbaits"][i])
    
    df["AvgWordLength"][i] = avgWordLength
    df["StoptoContent"][i] = stopWordtoContentWord

/home/prajwol/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/prajwol/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/home/prajwol/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [53]:
df.head(20)

,Unnamed: 0,Clickbaits,bait,Length,AvgWordLength,StoptoContent
0,0,Declassified records show American inaction du...,0,77.0,6.800000,0.200000
1,1,Indian Maoists blamed for the deaths of sixtee...,0,57.0,5.444444,0.333333
2,2,Yahoo!7 creates joint venture with Xtra,0,39.0,5.666667,0.166667
3,3,Only Solve This Puzzle If You Love Board Games,1,46.0,4.222222,0.444444
4,4,Three dead in murder-suicide shooting at South...,0,81.0,6.454545,0.272727
5,5,"""Love Actually"" Brings Together Every Fandom E...",1,74.0,5.818182,0.363636
6,6,Summers Says Stimulus Plan on Track Despite Jo...,0,54.0,5.111111,0.111111
7,7,California Warns of Layoffs at Schools,0,38.0,5.500000,0.333333
8,8,This Kid And Her Dad Teaching Their Dog How To...,1,66.0,3.785714,0.571429
9,9,The Food Porn Industry Will Never Be The Same ...,1,85.0,4.733333,0.600000
10,10,How Wild Was Your Weekend,1,25.0,4.200000,0.600000
11,11,"Hey Indian Politicians, You're Totally Asking ...",1,82.0,5.384615,0.307692
12,12,Australian rules football: West Gippsland Latr...,0,89.0,6.500000,0.083333
13,13,2007 U-17 FIFA World Cup:Germany and Colombia ...,0,62.0,5.300000,0.200000
14,14,The Strange Case Of The Woman Whose Skin Was T...,1,63.0,3.923077,0.538462
15,15,McClatchy Plans to Cut 15% of Its Work Force,0,44.0,4.000000,0.333333
16,16,15 Totally Breathtaking Places You Won't Belie...,1,57.0,5.444444,0.222222
17,17,US Singer Brandy involved in fatal car crash; ...,0,66.0,4.583333,0.250000
18,18,A Slight Upgrade in Quarterly G.D.P.,0,36.0,5.166667,0.333333
19,19,House Democrats Release Details of Their Tax Plan,0,49.0,5.250000,0.250000

In [54]:
df.to_csv("./featurextacted.csv")